hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "3f571bb934aaf3a5a1710f615e9903be6e8777319b606b95189113db52bf0198"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "12a7f8d7a7114bad88ad469f59bb5d4415057bdc4b4215bf29462508c39c9a46"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/citresewn.json"
hash = "057e9e53790394db8b700616de3c235b0af3dc12fe7731a66ad20026acb9d991"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "375d545e83e1aabc7700c5f0bea4f7bcf1a19e5e35f9a2155bde2e1c9b0ebc61"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "f5ff731194f66727bfeb75a28a70104fc4687cbc84b69e60c94fe1b7d901f453"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/isxander-main-menu-credits.json"
hash = "e9c780a3548faea77d7230f83a97497cf30ae5148d1855c632310f6fb69a5cec"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "786f832a586765c933b70dd47675608323a351bb7a958ef50de5dddf8d9b308e"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modernfix-mixins.properties"
hash = "ff2fb838e13e529a5939896a0775595c2e0c9d1288c7afca76ff1d3fd5646c97"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "b7b9cdc1e99bdfd86052e373dc3e0ae87c73760816454b801b09d0cfd7b79604"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/rrls.toml"
hash = "3630be880dc7f037238b7e6347201d4f716ffc7e16db0a1498ef2f775cf8f5be"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/yosbr/options.txt"
hash = "ef6e916dd12fe398041c063a7a0b70e8c8bdb6d4fb75533d3d14283337fd1654"

[[files]]
file = "mods/animatica.pw.toml"
hash = "90ef04eb585236f69ddb527455a740f8c945781e021c3ec3355c7ffad1ee4f00"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "b1e08d3a6db8777433227b2b300c89795d7baced15a012fe256aaddef74e91b6"
metafile = true

[[files]]
file = "mods/bettergrass.pw.toml"
hash = "2ed94b261b3e0496f84ab57927ccf54fbe1c5ea99482c9b7aabfe29f708d2776"
metafile = true

[[files]]
file = "mods/bettermounthud.pw.toml"
hash = "d83c777b94bfed67cdcb4b6eba1586a89e8d526c7c8765f3ad07e669cc73b5e8"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
hash = "5e097f95b8818e0999b4e867351745441f90c9bcf2a9c68cd19d5d708da4a4a1"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "b557acf03f54ba9bcea04ed559b316135b215aafa00b01d16553081f974b50bf"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "4548677ce03174ad536896e445cb4b77f7757bdfa957592084ea31b02941b2c7"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ededc607420a5486383ad58f9e92bce1c59bace57eeb1e5064e8994edd122bfa"
metafile = true

[[files]]
file = "mods/dynamic_fps.pw.toml"
hash = "af8dc072b8d618de96260fccfa5fab7f79c5ca9679bc3a57473f6df4ce218fff"
metafile = true

[[files]]
file = "mods/e4mc_minecraft.pw.toml"
hash = "71668946549848d55d39a6147813d11a9f7e2d5fb27205cc5374b85a8929fb88"
metafile = true

[[files]]
file = "mods/entity_model_features.pw.toml"
hash = "a11fca35f60d6a96e5b2dea303f6ea62519c1654c748bddad238285a65df485a"
metafile = true

[[files]]
file = "mods/entity_texture_features.pw.toml"
hash = "9d0a46f6b83448479d36f1c3df0e8487a5f586d8e7580b9ff8c04ca6bb2c04ab"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "af3a0307e844e8828258b8270d3507c270bcb8c47d9e1171c41ceacc77db1cd2"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "39b4f43a271700276ff1ae632cf05f90b85f79670d955b50ced036e363a0efe9"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2831d2be7f52107b8cb23145f8812485c7ee12107a4eabf47d39d5b5d778cf04"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "fcdaaad3ac86edfe8b2dd506b9e1303c70636251fc275f21f7a4a2efa324a8e8"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "8533ce030f217cfbe8d60ff6dbb76d9697b6589a3918d933e1810359eeefd3b7"
metafile = true

[[files]]
file = "mods/forgeconfigapiport.pw.toml"
hash = "f21073ecab797a66025836a6fd6deeb43e2a42d5e711aa8aaf6ce84cc4ece7c0"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "510cc5e208dd942ebf7593a51417630eabe02a2084943ca4adb276b194448313"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4df808c299fd18fd57b6f9f1997d89cdcbcbddf3472136b067a57979969af04e"
metafile = true

[[files]]
file = "mods/isxander-main-menu-credits.pw.toml"
hash = "bb039470d6643b00dca912699715ba1c7264c2e7f5a617c4417b0aee53bf24a8"
metafile = true

[[files]]
file = "mods/lambdynlights.pw.toml"
hash = "5901c63afe1e2a5c3f48937928bc4918ef3736bbce9f815796ef6ba5014ea908"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "d092368596299fdea95ebc92ca2ff45e2032444e6f9c6504669402f935d63e17"
metafile = true

[[files]]
file = "mods/mcqoy.pw.toml"
hash = "21e7b044769bec86617cb335296c1ab8c44b2ff374a8c3b214fea8e23466786b"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6cd55df8041a48cb7f5f95ea4520f5ed59064e71ff9dab8b0e02bb922b68c9cb"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "cc247f7ec018cf1517317e83efdbbbd573071bfbbfbc0d59faf1ce0152db2326"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "5deffbe5d244112ea021025973aec4728d2381ef24d240de5a9c28dbad14dfe1"
metafile = true

[[files]]
file = "mods/nochatreports.pw.toml"
hash = "614832d202c0033ee565bbac82d8762f66cb71be1616742939f77c43c65af458"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "c3d94092bb3887584f87ceb9d453e199f8c9325bdbf5c56447cb27d09f23e2af"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "f1aa887baa2d8756d63ee5b7d77983cab674cb2cc28ec546b7bde417c0f9a553"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "97754a77c90736daa9e20f8400c399addcb1156cbfead9c7f0ebcc17e3d43762"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "92b4f91faba008939cbe81ff534083d320623868dd9995c6d0368e64c43ab678"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "db278da4715600e9b96dfd79437f9cd70c5dfb7502be462dff790d570a9fb003"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "a6ecdb9d74d025a26a0d4a3815a60b01b6495f88f87a2249b46c1f883444a183"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "d8e1c8d570cb19aafa17aa9e98a4c6c683853fec2c9cf58e89660ce4e2ad51ba"
metafile = true

[[files]]
file = "mods/sspb.pw.toml"
hash = "f28799b3ee44dddc0fa2eaa9cdac49456ee69bae90f5ff27e7fc7f4e1b78fe54"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "b97b297fab12e137c58874ae776402cfa29374c8ff50c9f18ef27442b65336e6"
metafile = true

[[files]]
file = "mods/yet_another_config_lib_v3.pw.toml"
hash = "b8df62f282af4313eb6ce0c9504ab81c4ef690bf6ccb44b27113310579197707"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "3bf16ef57d8e5a916e8971ab9cc7cd90644d82932233b7e1e2293d95680fac4b"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "19f3f11ff12391852ca63b17b8691bfdf8ad9586635fbb7f66346a998f7cc751"
metafile = true

[[files]]
file = "resourcepacks/Chat_Reporting_Helper.pw.toml"
hash = "8df4154a6e955dbb60b44515414076324a06c9d539840157c5653d257642d134"
metafile = true

[[files]]
file = "resourcepacks/Translations_for_Sodium.pw.toml"
hash = "d77dfc3bf13ca53b19b15564800167012835deab25e6a97a09b4a699bd5843e8"
metafile = true

[[files]]
file = "servers.dat"
hash = "e2c8e8472163e69ffe0594785e78cea25d76e1fce5f95b95fa0480795274e981"
