name = "Fabulously Optimized"
author = "macuguita, nicole, marco, dylan kennedy"
version = "12.0.0-alpha.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "880764e720b59d98912280c20e56111678026addf7294a6c0d8e09e8fce4aa05"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
