name: Build and Publish Pack

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-22.04

    steps:
      # Checkout repository with submodules
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # Validate Gradle wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v5.0.0

      # Setup Java
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v5.1.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Install Packwiz CLI
      - name: Setup Go and install Packwiz
        uses: actions/setup-go@v6.1.0
        with:
          go-version: '1.25.5'
      - run: go install github.com/packwiz/packwiz@latest

      # Update submodule to latest commit
      - name: Update submodule
        run: git submodule update --init --recursive --remote

      # Build mod
      - name: Build mod
        run: |
          cd mod
          chmod +x ./gradlew
          ./gradlew build --no-daemon

      # Copy mod JAR into pack and refresh Packwiz
      - name: Prepare Packwiz pack
        run: |
          mkdir -p mods
          find mod/build/libs -maxdepth 1 -name '*.jar' ! -name '*-sources.jar' -exec cp {} mods/ \;
          packwiz refresh --build

          # Prepare build folder for GitHub Pages
          rm -rf build
          mkdir -p build
          rsync -av --exclude-from='.packwizignore' ./ build/

      # Upload to GitHub Pages
      - name: Upload Pages Artifacts
        uses: actions/upload-pages-artifact@v4.0.0
        id: deployment
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
